//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garage_gestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicules()
        {
            this.Services = new HashSet<Services>();
        }
    
        public int ID { get; set; }
        public string Marque { get; set; }
        public string Modele { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<int> FournisseurID { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Fournisseurs Fournisseurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
    }
}
